### Prueba de vida
GET http://localhost:3000/api/test

### Registrar un nuevo usuario
POST http://localhost:3000/api/v1/singup
Content-Type: application/json
{
    "name": "Juan Perez",
    "password": "123456",
    "email": "jp@gmail.com"
}

### Iniciar sesión
POST http://localhost:3000/api/v1/login
Content-Type: application/json
{
    "password": "123456",
    "email": "jp@gmail.com"
}

### se puede borrar
# > {% 
# // Parseamos JSON y guardamos token globalmente
# const body = response.json(); 
# client.global.set("token", body.token); 
# %}

### Obtener todas las tareas
### se puede usar (Libros)
GET http://localhost:3000/api/v1/toDos
Authorization: Bearer <token_aquí>

### Obtener una tarea por ID
### se puede usar (Libro)
GET http://localhost:3000/toDos/1 HTT/1.1
Content-Type: application/json
Authorization: Bearer <token_aquí>

### Obtener todos los usuarios (ruta privada)
### se puede borrar 
GET http://localhost:3000/api/v1/users
Authorization: Bearer <token_aquí>

### Crear una nueva tarea
### se puede usar (Categoria/Libro)
POST http://localhost:3000/api/v1/toDos HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token_aquí>
{
    "title": "Nueva Tarea"
}

### Actualizar una tarea por ID
### se puede usar (Libro/Usuario)
PUT http://localhost:3000/api/v1/toDos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token_aquí>
{
    "title": "Tarea Actualizada",
    "completed": false
}

### borrar una tarea
### se puede usar (Libro)
DELETE http://localhost:3000/api/v1/toDos/1

### sin ruta asociada
GET http://localhost:3000/api/v1/ii

### obtner tarea 
### se puede usar (Categoria/Libro)
GET http://localhost:3000/api/v1/toDos  
Authorization: 123

### crear un usuario
### se puede usar (Libro/Categoria)
POST http://localhost:3000/api/v1/usuarios HTTP/1.1
content-type: application/json
{
    "name": "Primer tarea", 
    "password":"123"
}

### crear un usuario
### se puede usar (Libro/Categoria)
GET http://localhost:3000/api/v1/login
content-type: application/json
{
    "name": "Juan Perez",
    "password": "123456"
}